- type: entity
  id: PaperPrinterCircuitboard
  parent: BaseMachineCircuitboard
  name: printer machine board
  description: A machine printed circuit board for a printer.
  components:
    - type: MachineBoard
      prototype: PaperPrinter
      requirements:
        MatterBin: 2
        Manipulator: 2
