using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Maths; // #SB AndreyCamper

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NavInterfaceState scc)
    {
        RadarScreen.UpdateState(scc);
    }
    // #SB AndreyCamper start
	public void UpdateRadarObjects(List<(NetCoordinates, Angle, byte)> projectiles,
        List<(NetCoordinates, Angle, float, byte)> lasers)
    {
        RadarScreen.UpdateRadarObjects(projectiles, lasers);
    }
    // #SB AndreyCamper end
}
