# НЕ ДЛЯ КОМАНДОВАНИЯ СТАНЦИИ

- type: job
  id: BlueshieldOfficer
  name: job-name-blueshield-officer
  description: job-description-blueshield
  playTimeTracker: JobBlueshieldOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Command
    time: 5h
  - !type:DepartmentTimeRequirement
    department: Security
    time: 30h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 10h
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Muted
  startingGear: BlueshieldOfficerGear
  icon: "JobIconERTSecurity"
  supervisors: job-supervisors-centcom
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    head: ClothingHeadHatBeretBlueshieldOfficer
    jumpsuit: ClothingUniformJumpsuitBluesheildOfficer
    back: ClothingBackpackBlueshieldOfficer
    mask: ClothingMaskGasSecurity
    shoes: ClothingShoesBootsJackFilled
    eyes: ClothingEyesVisorTactical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorBlueshieldOfficer
    id: BlueshieldOfficerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltAssault
    pocket1: TelescopicShield
    pocket2: DoorRemoteCustom
    suitstorage: WeaponEnergyRevolverBlueshield
  storage:
    back:
    - Flash
    - MedkitCombatFilled
    - BodyBagFolded
    - WeaponSubMachineGunAtreides # Хороший телохранитель же не будет держать своё главное оружие на виду, верно?
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - AdvancedJetInjector
    - ChemistryBottleDexalinPlus
    - ChemistryBottleTranexamicAcid
    - ChemistryBottleOmnizine
    - ChemistryBottleOmnizine
    belt:
    - JawsOfLife
    - Stunbaton
    - HoloprojectorSecurity
    - GrenadeFlashBang
    - GrenadeFlashBang
    - GrenadeStinger
    - Handcuffs
    - Zipties
    - Zipties