# Без роли. Просто задуманные специализации офицеров, отличающиеся лишь визуально. Оператор это просто офицер вот так вот

- type: startingGear
  id: CentcomInternalOversightOfficerGear
  equipment:
    head: ClothingHeadHatCentcomcap
    neck: ClothingNeckMantleCentcom
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    back: ClothingBackpackSatchelCorporate
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCentcomNaval
    id: CentcomOfficerPDA
    ears: ClothingHeadsetCentCom
    belt: WeaponPistolN1984
    pocket1: WeaponDisabler
    pocket2: NanotrasenFlippo
  storage:
    back:
    - Flash
    - CigarGoldCase
    - MagazineMagnum
    - MagazineMagnum
    - Handcuffs
    - BoxFolderCentComThreePapers
    - RubberStampCentcom
    - RubberStampApproved
    - RubberStampDenied
    - DoorRemoteCustom

- type: startingGear
  id: CentcomHROfficerGear
  equipment:
    head: ClothingHeadHatBeretCentcomNaval
    jumpsuit: ClothingUniformJumpsuitCentcomOfficerShirt
    back: ClothingBackpackSatchelCorporate
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCentcomNaval
    outerClothing: ClothingOuterCoatCentcom
    id: CentcomOfficerPDA
    ears: ClothingHeadsetCentCom
    belt: BoxFolderCentComClipboardThreePapers
    pocket1: WeaponPistolN1984
    pocket2: NanotrasenFlippo
  storage:
    back:
    - Flash
    - CigarGoldCase
    - MagazineMagnum
    - MagazineMagnum
    - BoxFolderCentComThreePapers
    - BoxFolderRedEmpty
    - RubberStampCentcom
    - RubberStampApproved
    - RubberStampDenied
    - DoorRemoteCustom

- type: startingGear
  id: CentcomAccountingOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomAgent
    back: ClothingBackpackSatchelCorporate
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesHop
    id: CentcomOfficerPDA
    ears: ClothingHeadsetCentCom
    belt: BoxFolderCentComClipboardThreePapers
    pocket1: WeaponPistolN1984
    pocket2: NanotrasenFlippo
  storage:
    back:
    - Flash
    - CigarGoldCase
    - MagazineMagnum
    - MagazineMagnum
    - BoxFolderCentComThreePapers
    - BoxFolderRedEmpty
    - RubberStampCentcom
    - RubberStampApproved
    - RubberStampDenied
    - DoorRemoteCustom
