- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Highpop
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
  - Bagel
  - Box
  # Midpop
  - CorvaxCuteInstallation
  - CorvaxPaper
  - CorvaxOutpost
  - CorvaxAwesome
  - CorvaxPearl
  - Amber
  - Marathon
  # Lowpop
  - CorvaxSilly
  - CorvaxMaus
  - CorvaxTushkan
  - Omega
  - Packed
