using System.Linq;
using Content.Client.Corvax.Lobby;
using Content.Client.Corvax.Lobby.Systems;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Corvax.CCCVars;
using Robust.Client;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Configuration;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Log;
using Robust.Shared.Serialization.Manager;
using Robust.Shared.Serialization.Markdown;
using Robust.Shared.Serialization.Markdown.Mapping;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Corvax.Lobby.UI;

/// <summary>
/// Displays a portable, resource-configured list of servers in the lobby.
/// Successful connections are handed back to the launcher so servers on other
/// forks can load the correct content build.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyServerHub : BoxContainer
{
    private static readonly ResPath ConfigPath = new("/ServerInfo/Corvax/lobby-servers.yml");
    [Dependency] private IGameController _gameController = default!;
    [Dependency] private IConfigurationManager _configuration = default!;
    [Dependency] private IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private ILocalizationManager _localization = default!;
    [Dependency] private ILogManager _logManager = default!;
    [Dependency] private IResourceManager _resourceManager = default!;
    [Dependency] private ISerializationManager _serialization = default!;
    [Dependency] private IUserInterfaceManager _userInterfaceManager = default!;

    private ISawmill _sawmill = default!;
    private LobbyServerHubSystem? _statusSystem;
    private readonly List<ServerRow> _rows = new();
    private string[] _addresses = Array.Empty<string>();
    private int _statusRevision = -1;
    private bool _showAdult;
    private bool _scrollAdultToEnd;

    public LobbyServerHub()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("corvax.lobby-server-hub");
        CollapseButton.OnPressed += _ => SetCollapsed(true);
        ExpandButton.OnPressed += _ => SetCollapsed(false);
        ServerGrid.OnResized += ScrollAdultToEnd;
        LoadServers();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _configuration.OnValueChanged(CCCVars.LobbyServerHubEnabled, OnEnabledChanged, true);
    }

    protected override void ExitedTree()
    {
        _configuration.UnsubValueChanged(CCCVars.LobbyServerHubEnabled, OnEnabledChanged);
        base.ExitedTree();
    }

    private void OnEnabledChanged(bool enabled)
    {
        Visible = enabled && _rows.Count > 0;
    }

    private void LoadServers()
    {
        try
        {
            if (!_resourceManager.ContentFileExists(ConfigPath))
            {
                _sawmill.Warning($"Lobby server hub config does not exist: {ConfigPath}");
                return;
            }

            var yaml = _resourceManager.ContentFileReadYaml(ConfigPath);
            if (yaml.Documents.Count == 0 || yaml.Documents[0].RootNode.ToDataNode() is not MappingDataNode root)
            {
                _sawmill.Error($"Lobby server hub config must contain a YAML mapping: {ConfigPath}");
                return;
            }

            var config = _serialization.Read<LobbyServerHubConfig>(root, notNullableOverride: true);
            var configuredServers = config.Primary
                .Select(server => (Server: server, Section: LobbyServerSection.Primary))
                .Concat(config.Subprojects.Select(server =>
                    (Server: server, Section: LobbyServerSection.Subprojects)));

            foreach (var (configured, index) in configuredServers
                         .Select((configured, index) => (configured, index)))
            {
                var (server, section) = configured;
                if (!server.TryGetAddress(out var address))
                {
                    _sawmill.Warning("Ignoring invalid lobby server entry: expected an ss14:// or ss14s:// address.");
                    continue;
                }

                var row = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    SeparationOverride = 3,
                };
                var rowContent = new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 6,
                };
                var serverInfo = new BoxContainer
                {
                    Orientation = LayoutOrientation.Vertical,
                    HorizontalExpand = true,
                    SeparationOverride = 1,
                };
                var button = new Button
                {
                    Text = GetFallbackName(address),
                    ToolTip = address,
                    HorizontalExpand = true,
                    TextAlign = Label.AlignMode.Left,
                };
                var map = new Label
                {
                    Text = Loc.GetString("corvax-lobby-server-hub-map-unavailable"),
                    ClipText = false,
                    HorizontalExpand = true,
                    StyleClasses = { "LabelSubText" },
                };
                var preset = new Label
                {
                    Text = Loc.GetString("corvax-lobby-server-hub-preset-unavailable"),
                    ClipText = false,
                    Align = Label.AlignMode.Right,
                    StyleClasses = { "LabelSubText" },
                };
                var details = new WrapContainer
                {
                    LayoutAxis = Axis.Horizontal,
                    HorizontalExpand = true,
                    SeparationOverride = 6,
                    CrossSeparationOverride = 1,
                    Children =
                    {
                        map,
                        preset,
                    },
                };
                var status = new Label
                {
                    Text = Loc.GetString("corvax-lobby-server-hub-online-loading"),
                    ToolTip = Loc.GetString("corvax-lobby-server-hub-online-tooltip"),
                    MinWidth = 64,
                    MaxWidth = 64,
                    MinHeight = 28,
                    Align = Label.AlignMode.Right,
                    VAlign = Label.VAlignMode.Center,
                    VerticalAlignment = VAlignment.Top,
                };

                button.OnPressed += _ => Connect(address);
                serverInfo.AddChild(button);
                serverInfo.AddChild(details);
                rowContent.AddChild(serverInfo);
                rowContent.AddChild(CreateDivider(vertical: true));
                rowContent.AddChild(status);
                row.AddChild(rowContent);
                row.AddChild(CreateDivider(vertical: false));
                ServerGrid.AddChild(row);
                var serverRow = new ServerRow(
                    index,
                    address,
                    section,
                    server.Adult,
                    row,
                    button,
                    map,
                    preset,
                    status);
                _rows.Add(serverRow);
            }

            _addresses = _rows.Select(row => row.Address).ToArray();
            SortByOnline();
            Visible = _configuration.GetCVar(CCCVars.LobbyServerHubEnabled) && ServerGrid.ChildCount > 0;
        }
        catch (Exception exception)
        {
            _sawmill.Error($"Failed to load lobby server hub config {ConfigPath}: {exception}");
        }
    }

    private static PanelContainer CreateDivider(bool vertical)
    {
        return new PanelContainer
        {
            MinWidth = vertical ? 1 : 0,
            MinHeight = vertical ? 0 : 1,
            VerticalExpand = vertical,
            HorizontalExpand = !vertical,
            Margin = vertical ? new Thickness(0, 2) : new Thickness(0),
            StyleClasses = { StyleClass.LowDivider },
        };
    }

    private static string GetFallbackName(string address)
    {
        var schemeEnd = address.IndexOf("://", StringComparison.Ordinal);
        return (schemeEnd >= 0 ? address[(schemeEnd + 3)..] : address).TrimEnd('/');
    }

    private string LocalizePreset(string preset)
    {
        var trimmed = preset.Trim();
        var detailsStart = trimmed.IndexOf('(');
        if (detailsStart >= 0)
            trimmed = trimmed[..detailsStart].TrimEnd();

        return _localization.TryGetString(trimmed, out var localized) ? localized : trimmed;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!Visible || _addresses.Length == 0)
            return;

        _statusSystem ??= _entitySystemManager.GetEntitySystemOrNull<LobbyServerHubSystem>();
        if (_statusSystem == null)
            return;

        _statusSystem.RequestUpdate(_addresses);
        if (_statusSystem.Revision == 0 || _statusRevision == _statusSystem.Revision)
            return;

        _statusRevision = _statusSystem.Revision;
        foreach (var row in _rows)
        {
            row.IsCurrent = _statusSystem.IsCurrentServer(row.Address);

            if (!_statusSystem.TryGetStatus(row.Address, out var status))
            {
                row.Players = null;
                row.Status.Text = Loc.GetString("corvax-lobby-server-hub-online-unavailable");
                continue;
            }

            row.Players = status.Players;
            if (!string.IsNullOrWhiteSpace(status.Name))
                row.Button.Text = status.Name.Trim();
            // Hub can briefly omit the map while a server is restarting. Keep
            // the last known value instead of flashing an empty map field.
            if (!string.IsNullOrWhiteSpace(status.Map))
            {
                row.Map.Text = Loc.GetString("corvax-lobby-server-hub-map", ("map", status.Map));
            }
            if (!string.IsNullOrWhiteSpace(status.Preset))
            {
                var localizedPreset = LocalizePreset(status.Preset);
                row.Preset.Text = Loc.GetString(
                    "corvax-lobby-server-hub-preset",
                    ("preset", localizedPreset));
                row.Preset.ToolTip = localizedPreset;
            }
            row.Status.Text = status.SoftMaxPlayers is { } softMax
                ? $"{status.Players}/{softMax}"
                : status.Players.ToString();
        }

        SortByOnline();
    }

    private void SortByOnline()
    {
        if (ColumnHeader.Parent is { } headerParent && headerParent != ServerGrid)
            headerParent.RemoveChild(ColumnHeader);

        ServerGrid.RemoveAllChildren();

        var currentServerIsAdult = _rows.Any(row => row.Adult && row.IsCurrent);

        var columnHeaderAdded = false;
        foreach (var section in Enum.GetValues<LobbyServerSection>())
        {
            var sectionRows = _rows
                .Where(row => row.Section == section &&
                    !row.IsCurrent &&
                    (_statusRevision < 0 || row.Players != null))
                .ToArray();
            if (sectionRows.Length == 0)
                continue;

            var sectionLabel = new Label
            {
                Text = Loc.GetString(section switch
                {
                    LobbyServerSection.Primary => "corvax-lobby-server-hub-primary-heading",
                    LobbyServerSection.Subprojects => "corvax-lobby-server-hub-subprojects-heading",
                    _ => throw new ArgumentOutOfRangeException(nameof(section), section, null),
                }),
                HorizontalAlignment = HAlignment.Center,
                StyleClasses = { StyleClass.LabelKeyText },
            };

            if (!columnHeaderAdded)
            {
                var combinedHeader = new PanelContainer
                {
                    HorizontalExpand = true,
                    Children =
                    {
                        ColumnHeader,
                        sectionLabel,
                    },
                };
                ServerGrid.AddChild(combinedHeader);
                columnHeaderAdded = true;
            }
            else
            {
                ServerGrid.AddChild(sectionLabel);
            }

            ServerGrid.AddChild(new HLine
            {
                Thickness = 2,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
                StyleClasses = { StyleClass.Highlight },
            });

            AddSortedRows(sectionRows.Where(row => !row.Adult));

            var adultRows = sectionRows.Where(row => row.Adult).ToArray();
            if (adultRows.Length == 0)
                continue;

            if (currentServerIsAdult)
            {
                AddSortedRows(adultRows);
                continue;
            }

            var adultToggle = new Button
            {
                Text = Loc.GetString(_showAdult
                    ? "corvax-lobby-server-hub-hide-adult"
                    : "corvax-lobby-server-hub-show-adult"),
                HorizontalAlignment = HAlignment.Left,
            };
            adultToggle.OnPressed += _ =>
            {
                _showAdult = !_showAdult;
                _scrollAdultToEnd = _showAdult;
                SortByOnline();
            };
            ServerGrid.AddChild(adultToggle);

            if (_showAdult)
                AddSortedRows(adultRows);
        }

        // This spacer belongs to the scrollable content so the final row or
        // the 18+ toggle can be scrolled fully clear of the panel edge.
        ServerGrid.AddChild(new Control { MinHeight = 18 });
    }

    private void ScrollAdultToEnd()
    {
        if (!_scrollAdultToEnd)
            return;

        _scrollAdultToEnd = false;
        ServerScroll.VScrollTarget = float.MaxValue;
    }

    private void AddSortedRows(IEnumerable<ServerRow> rows)
    {
        foreach (var row in rows
                     .OrderBy(row => row.Players == null)
                     .ThenByDescending(row => row.Players)
                     .ThenBy(row => row.ConfigIndex))
        {
            ServerGrid.AddChild(row.Control);
        }
    }

    private void SetCollapsed(bool collapsed)
    {
        ExpandedPanel.Visible = !collapsed;
        CollapsedPanel.Visible = collapsed;
    }

    private void Connect(string address)
    {
        try
        {
            _gameController.Redial(
                address,
                Loc.GetString("corvax-lobby-server-hub-redial-reason"));
        }
        catch (Exception exception)
        {
            _sawmill.Error($"Unable to redial to {address}: {exception}");
            _userInterfaceManager.Popup(
                Loc.GetString("corvax-lobby-server-hub-connect-failed"),
                Loc.GetString("corvax-lobby-server-hub-connect-failed-title"));
        }
    }

    private sealed class ServerRow(
        int configIndex,
        string address,
        LobbyServerSection section,
        bool adult,
        BoxContainer control,
        Button button,
        Label map,
        Label preset,
        Label status)
    {
        public int ConfigIndex { get; } = configIndex;
        public string Address { get; } = address;
        public LobbyServerSection Section { get; } = section;
        public bool Adult { get; } = adult;
        public BoxContainer Control { get; } = control;
        public Button Button { get; } = button;
        public Label Map { get; } = map;
        public Label Preset { get; } = preset;
        public Label Status { get; } = status;
        public int? Players { get; set; }
        public bool IsCurrent { get; set; }
    }
}
