using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;

namespace Content.Client.Administration.UI.Tabs.SponsorTab;

[GenerateTypedNameReferences]
public sealed partial class SponsorTabHeader : ContainerButton
{
    public SponsorTabHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
