using System.Linq;
using Content.Client.Options.UI;
using Content.Client.Stylesheets;
using Content.Shared.Corvax.CCCVars;
using Content.Shared.Corvax.TTS;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Corvax.Options.UI.Tabs;

/// <summary>
/// TTS Control with all settings
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class TTSControl : Control
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private readonly Dictionary<Button, RadioChannelFlag> _radioButtons = new();
    private OptionsTabControlRow _controlRow = default!;

    public const float TtsMultiplier = 3f;

    public TTSControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Initialize(OptionsTabControlRow controlRow)
    {
        _controlRow = controlRow;

        InitializeControls();
        PopulateVoiceEffectOptions();
        BuildRadioFilterLogic();
    }

    private void InitializeControls()
    {
        // TTS Volume
        _controlRow.AddOptionPercentSlider(
            CCCVars.TTSVolume,
            SliderVolumeTts,
            scale: TtsMultiplier);

        // TTS Radio Volume
        _controlRow.AddOptionPercentSlider(
            CCCVars.TTSRadioVolume,
            SliderVolumeTtsRadio,
            scale: TtsMultiplier);
    }

    private void PopulateVoiceEffectOptions()
    {
        VoiceEffectOption.Clear();

        foreach (TTSVoiceEffectPreset preset in Enum.GetValues(typeof(TTSVoiceEffectPreset)))
        {
            var displayName = Loc.GetString($"tts-efx-effect-{preset.ToString().ToLowerInvariant()}");
            VoiceEffectOption.AddItem(displayName, (int)preset);
        }

        var currentValue = _cfg.GetCVar(CCCVars.TTSVoiceEffect);
        VoiceEffectOption.SelectId(currentValue);

        VoiceEffectOption.OnItemSelected += OnVoiceEffectSelected;
    }

    private void OnVoiceEffectSelected(OptionButton.ItemSelectedEventArgs args)
    {
        var preset = (TTSVoiceEffectPreset)args.Id;
        VoiceEffectOption.SelectId(args.Id);

        _cfg.SetCVar(CCCVars.TTSVoiceEffect, (ushort)preset);
        _cfg.SaveToFile();
    }

    private void BuildRadioFilterLogic()
    {
        AllRadioButton.OnPressed += _ => SetAllRadioFilter(true);
        NoneRadioButton.OnPressed += _ => SetAllRadioFilter(false);
        ResetRadioButton.OnPressed += _ => ResetRadioFilter();

        var flags = Enum.GetValues(typeof(RadioChannelFlag))
            .Cast<RadioChannelFlag>()
            .Where(f => f != RadioChannelFlag.None && f != RadioChannelFlag.AllExceptCommon
                && f != RadioChannelFlag.All && ((int)f & ((int)f - 1)) == 0);

        var currentFilter = (RadioChannelFlag)_cfg.GetCVar(CCCVars.TTSRadioFilter);

        foreach (var flag in flags)
        {
            var flagName = flag.ToString().ToLowerInvariant();
            var button = new Button
            {
                Text = Loc.GetString($"chat-radio-{flagName}"),
                ToggleMode = true,
                Pressed = currentFilter.HasFlag(flag),
                Margin = new Thickness(2, 2, 2, 2),
                HorizontalExpand = true
            };

            _radioButtons[button] = flag;

            if (button.Pressed)
            {
                button.AddStyleClass(StyleClass.Positive);
            }

            button.OnToggled += OnRadioFilterToggled;
            RadioFilterGrid.AddChild(button);
        }
    }

    private void OnRadioFilterToggled(BaseButton.ButtonToggledEventArgs args)
    {
        var button = (Button)args.Button;
        if (!_radioButtons.TryGetValue(button, out var flag))
            return;

        var currentFilter = (RadioChannelFlag)_cfg.GetCVar(CCCVars.TTSRadioFilter);

        if (args.Pressed)
        {
            currentFilter |= flag;
            button.AddStyleClass(StyleClass.Positive);
        }
        else
        {
            currentFilter &= ~flag;
            button.RemoveStyleClass(StyleClass.Positive);
        }

        _cfg.SetCVar(CCCVars.TTSRadioFilter, (ushort)currentFilter);
        _cfg.SaveToFile();
    }

    private void SetAllRadioFilter(bool enabled)
    {
        var currentFilter = RadioChannelFlag.None;

        if (enabled)
        {
            var flags = Enum.GetValues(typeof(RadioChannelFlag))
                .Cast<RadioChannelFlag>()
                .Where(f => f != RadioChannelFlag.None && f != RadioChannelFlag.AllExceptCommon
                    && f != RadioChannelFlag.All && ((int)f & ((int)f - 1)) == 0);


            foreach (var flag in flags)
            {
                currentFilter |= flag;
            }
        }

        _cfg.SetCVar(CCCVars.TTSRadioFilter, (ushort)currentFilter);
        _cfg.SaveToFile();

        UpdateRadioFilterUI(currentFilter);
    }

    private void ResetRadioFilter()
    {
        var defaultFilter = RadioChannelFlag.AllExceptCommon;
        _cfg.SetCVar(CCCVars.TTSRadioFilter, (ushort)defaultFilter);
        _cfg.SaveToFile();

        UpdateRadioFilterUI(defaultFilter);
    }

    private void UpdateRadioFilterUI(RadioChannelFlag filter)
    {
        foreach (var (button, flag) in _radioButtons)
        {
            var isPressed = filter.HasFlag(flag);
            button.Pressed = isPressed;

            if (isPressed) button.AddStyleClass(StyleClass.Positive);
            else button.RemoveStyleClass(StyleClass.Positive);
        }
    }
}
