using System.Linq;
using System.Numerics;
using Content.Client.Corvax.SecApartment.Stylesheets;
using Content.Client.GameTicking.Managers;
using Content.Shared.SecApartment;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Corvax.SecApartment;

[Virtual]
[GenerateTypedNameReferences]
public sealed partial class SecApartmentWindow : BaseWindow
{
    [Dependency] private readonly IUserInterfaceManager _ui = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IGameTiming _gameTiming = default!;
    private readonly ClientGameTicker _gameTicker;
    private readonly SpriteSystem _sprite;

    private readonly SecApartmentStyles _styles;
    private string _station = Loc.GetString("sec-apartment-unknown");
    private Dictionary<string, SquadEntry> _squadEntries = new();
    private Dictionary<string, CrewMemberInfo> _lastCrewData = new();
    private Dictionary<NetEntity, TimerEntryControl> _timerControls = new();

    public Action<string>? OnCreateSquad;
    public Action<string, string>? OnRenameSquad;
    public Action<string>? OnDeleteSquad;
    public Action<string, string>? OnUpdateSquadDescription;
    public Action<string, SquadStatus>? OnChangeSquadStatus;
    public Action<string, string>? OnAddMemberToSquad;
    public Action<string, string>? OnRemoveMemberFromSquad;
    public Action<string, SquadIconNum>? OnChangeSquadIcon;
    public Action<NetEntity>? OnRemoveTimer;

    private Stylesheet? _previousGlobalStylesheet;

    public SecApartmentWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entitySystem.GetEntitySystem<SpriteSystem>();
        _gameTicker = _entitySystem.GetEntitySystem<ClientGameTicker>();
        _styles = new SecApartmentStyles(_resCache);

        SetupAllStyles();

        CloseButton.OnPressed += _ => Close();

        NewSquadName.OnTextChanged += OnSquadNameTextChanged;

        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
        CreateSquadButton.OnPressed += _ =>
        {
            if (!string.IsNullOrWhiteSpace(NewSquadName.Text))
            {
                var squadName = FormattedMessage.RemoveMarkupOrThrow(NewSquadName.Text);
                if (squadName.Length > 16) squadName = squadName[..16];

                OnCreateSquad?.Invoke(squadName);
                NewSquadName.Text = string.Empty;
                CreateSquadButton.Disabled = true;
            }
        };
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => DragMode.Move;

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var stationTime = _gameTiming.CurTime.Subtract(_gameTicker.RoundStartTimeSpan);
        StationLabel.Text = Loc.GetString("sec-apartment-ui-mark", ("time", stationTime.ToString("hh\\:mm\\:ss")), ("station", _station));
    }

    private void SetupAllStyles()
    {
        SetupBasicStyles();
        SetupTabContainer();
    }

    private void SetupBasicStyles()
    {
        StationLabel.FontColorOverride = SecApartmentStyles.HeadingColor;
        StationLabel.FontOverride = _styles.GetBoldFont(16);

        UnassignedCountLabel.FontColorOverride = SecApartmentStyles.TextColor;
        UnassignedCountLabel.FontOverride = _styles.GetRegularFont(13);

        SquadsCountLabel.FontColorOverride = SecApartmentStyles.TextColor;
        SquadsCountLabel.FontOverride = _styles.GetRegularFont(13);

        Footer.FontColorOverride = SecApartmentStyles.SubTextColor;
        Footer.FontOverride = _styles.GetRegularFont(11);

        StationLabel.AddStyleClass(SecApartmentStyles.StyleClassConsoleHeading);
        NewSquadName.AddStyleClass(SecApartmentStyles.StyleClassConsoleLineEdit);
        CreateSquadButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);

        var buttonStyleRule = SecApartmentStyles.CreateButtonRedRule(
            _styles.GetButtonRedStyle(),
            _styles.GetBoldFont(11),
            SecApartmentStyles.TabActiveColor,
            SecApartmentStyles.TabInactiveColor
        );

        var lineEditRule = SecApartmentStyles.CreateLineEditRule(
            _styles.GetLineEditStyle(),
            _styles.GetRegularFont(11),
            SecApartmentStyles.TextColor,
            SecApartmentStyles.PlaceholderColor
        );

        var optionRule = SecApartmentStyles.CreateOptionButtonRule(
            _styles.GetOptionButtonStyle(),
            _styles.GetRegularFont(11),
            SecApartmentStyles.TextColor,
            SecApartmentStyles.TabInactiveColor
        );

        var optionBackgroundRule = SecApartmentStyles.CreateOptionButtonBackgroundRule();

        var rules = new[] { buttonStyleRule, lineEditRule, optionRule, optionBackgroundRule };
        var stylesheet = CreateCombinedStylesheet(rules);

        _previousGlobalStylesheet = _ui.Stylesheet;
        UserInterfaceManager.Stylesheet = stylesheet;
    }
    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing && _previousGlobalStylesheet != null)
        {
            UserInterfaceManager.Stylesheet = _previousGlobalStylesheet;
        }
    }

    private void SetupTabContainer()
    {
        Tabs.SetTabTitle(0, Loc.GetString("sec-apartment-tab-squads"));
        Tabs.SetTabTitle(1, Loc.GetString("sec-apartment-tab-timers"));

        Tabs.TabFontColorOverride = SecApartmentStyles.TabActiveColor;
        Tabs.TabFontColorInactiveOverride = SecApartmentStyles.TabInactiveColor;

        var tabRule = SecApartmentStyles.CreateTabContainerRule(
            _styles.GetTabActiveStyle(),
            _styles.GetTabInactiveStyle(),
            _styles.GetPanelStyle(),
            _styles.GetBoldFont(),
            SecApartmentStyles.TabActiveColor,
            SecApartmentStyles.TabInactiveColor
        );

        Tabs.Stylesheet = CreateCombinedStylesheet(new[] { tabRule });
    }

    private Stylesheet CreateCombinedStylesheet(StyleRule[] additionalRules)
    {
        var existingStyles = _ui.Stylesheet;
        var combinedRules = new List<StyleRule>();

        if (existingStyles?.Rules != null)
            combinedRules.AddRange(existingStyles.Rules);

        combinedRules.AddRange(additionalRules);

        return new Stylesheet(combinedRules);
    }

    private void OnSquadNameTextChanged(LineEdit.LineEditEventArgs args)
    {
        CreateSquadButton.Disabled = string.IsNullOrWhiteSpace(NewSquadName.Text);
    }

    public void UpdateState(SecApartmentUpdateState state)
    {
        _station = state.StationName?.ToUpperInvariant() ?? Loc.GetString("sec-apartment-unknown");

        UpdateUnassignedList(state.UnassignedSecurity, state.Squads);
        UpdateSquadsList(state.Squads);
    }

    public void UpdateSensorStatuses(SensorStatusUpdateState sensorState)
    {
        foreach (var squadEntry in _squadEntries.Values)
        {
            squadEntry.UpdateSensorStatuses(sensorState.MemberStatuses, sensorState.SquadLocations);
        }
    }

    public void UpdateTimerState(TimerUpdateState state)
    {
        UpdateTimersList(state.Timers);
    }

    private void UpdateUnassignedList(List<CrewMemberInfo> unassigned, List<Squad> squads)
    {
        UnassignedCountLabel.Text = unassigned.Count.ToString();
        UnassignedContainer.Children.Clear();

        foreach (var member in unassigned)
        {
            SpriteSpecifier? iconSpecifier = null;
            if (_prototypeManager.HasIndex<JobIconPrototype>(member.JobIcon))
                iconSpecifier = _prototypeManager.Index<JobIconPrototype>(member.JobIcon).Icon;
            else if (_prototypeManager.HasIndex<StatusIconPrototype>(member.JobIcon))
                iconSpecifier = _prototypeManager.Index<StatusIconPrototype>(member.JobIcon).Icon;

            var entry = new CrewMemberEntry(member, squads, iconSpecifier, _sprite);
            entry.OnAssignPressed += squadId =>
                OnAddMemberToSquad?.Invoke(squadId, member.MemberId);
            UnassignedContainer.AddChild(entry);
        }
    }

    private void UpdateSquadsList(List<Squad> squads)
    {
        SquadsCountLabel.Text = squads.Count.ToString();
        SquadsContainer.Children.Clear();
        _squadEntries.Clear();

        foreach (var squad in squads)
        {
            var entry = new SquadEntry(squad, _styles, _prototypeManager, _sprite);
            entry.OnIconChanged += iconId =>
                OnChangeSquadIcon?.Invoke(squad.SquadId, iconId);
            entry.OnRenamePressed += newName =>
            {
                var cleanName = FormattedMessage.RemoveMarkupOrThrow(newName);
                if (cleanName.Length > 16) cleanName = cleanName[..16];

                OnRenameSquad?.Invoke(squad.SquadId, cleanName);
            };
            entry.OnDeletePressed += () =>
                OnDeleteSquad?.Invoke(squad.SquadId);
            entry.OnUpdateDescriptionPressed += description =>
                OnUpdateSquadDescription?.Invoke(squad.SquadId, description);
            entry.OnStatusChanged += status =>
                OnChangeSquadStatus?.Invoke(squad.SquadId, status);
            entry.OnRemoveMemberPressed += memberId =>
                OnRemoveMemberFromSquad?.Invoke(squad.SquadId, memberId);

            SquadsContainer.AddChild(entry);
            _squadEntries[squad.SquadId] = entry;

            foreach (var member in squad.Members)
            {
                _lastCrewData[member.MemberId] = member;
            }
        }
    }

    private void UpdateTimersList(List<TimerEntry> timers)
    {
        TimersCountLabel.Text = timers.Count.ToString();

        var toRemove = new List<NetEntity>();
        foreach (var (timerUid, control) in _timerControls)
        {
            if (!timers.Any(t => t.TimerUid == timerUid))
                toRemove.Add(timerUid);
        }

        foreach (var timerUid in toRemove)
        {
            if (_timerControls.TryGetValue(timerUid, out var control))
            {
                TimersContainer.Children.Remove(control);
                _timerControls.Remove(timerUid);
            }
        }

        foreach (var timer in timers)
        {
            if (!_timerControls.TryGetValue(timer.TimerUid, out var control))
            {
                control = new TimerEntryControl(timer, _styles);
                control.OnRemovePressed += () =>
                    OnRemoveTimer?.Invoke(timer.TimerUid);
                TimersContainer.AddChild(control);
                _timerControls[timer.TimerUid] = control;
            }
            else
            {
                control.UpdateTimer(timer);
            }
        }

        var sortedChildren = TimersContainer.Children
            .OfType<TimerEntryControl>()
            .OrderBy(t => t.RemainingTime.TotalSeconds)
            .ToList();

        TimersContainer.Children.Clear();
        foreach (var child in sortedChildren)
        {
            TimersContainer.AddChild(child);
        }
    }
}
