using System.Linq;
using System.Numerics;
using Content.Client.Corvax.SecApartment.Stylesheets;
using Content.Shared.Medical.SuitSensor;
using Content.Shared.SecApartment;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Corvax.SecApartment;

[GenerateTypedNameReferences]
public sealed partial class SquadEntry : PanelContainer
{
    private readonly IPrototypeManager _prototypeManager;
    private readonly SpriteSystem _sprite;

    public Squad Squad { get; }

    public Action<string>? OnRenamePressed;
    public Action? OnDeletePressed;
    public Action<string>? OnUpdateDescriptionPressed;
    public Action<SquadStatus>? OnStatusChanged;
    public Action<string>? OnRemoveMemberPressed;
    public Action<SquadIconNum>? OnIconChanged;

    private readonly SecApartmentStyles _styles;

    private bool _isEditingName = false;
    private bool _isEditingDescription = false;
    private Dictionary<string, PanelContainer> _memberPanels = new();

    public SquadEntry(Squad squad, SecApartmentStyles styles, IPrototypeManager protoMan, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        _prototypeManager = protoMan;
        _sprite = sprite;
        _styles = styles;
        Squad = squad;

        SetupStyles();
        SetupUI();
        UpdateUI();
    }

    private void SetupUI()
    {
        RenameButton.OnPressed += _ => ToggleNameEdit();
        DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke();
        EditDescriptionButton.OnPressed += _ => ToggleDescriptionEdit();
        SaveDescriptionButton.OnPressed += _ => SaveDescription();

        SetupIconDropdown();

        foreach (SquadStatus status in Enum.GetValues(typeof(SquadStatus)))
        {
            StatusDropdown.AddItem(GetStatusText(status), (int)status);
        }

        StatusDropdown.OnItemSelected += args =>
        {
            StatusDropdown.SelectId(args.Id);
            var status = (SquadStatus)args.Id;
            OnStatusChanged?.Invoke(status);
        };

        SaveNameButton.OnPressed += _ => SaveName();

        UpdateMembersList();
    }

    private void SetupStyles()
    {
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#4a1a1a"),
            BorderColor = SecApartmentStyles.TabActiveColor,
            BorderThickness = new Thickness(2),
            ContentMarginBottomOverride = 8,
            ContentMarginLeftOverride = 10,
            ContentMarginRightOverride = 10,
            ContentMarginTopOverride = 8
        };

        RenameButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        DeleteButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        EditDescriptionButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        SaveDescriptionButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);
        SaveNameButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);

        SquadNameEdit.AddStyleClass(SecApartmentStyles.StyleClassConsoleLineEdit);
        SquadDescriptionEdit.AddStyleClass(SecApartmentStyles.StyleClassConsoleLineEdit);

        IconDropdown.AddStyleClass(SecApartmentStyles.StyleClassOptionButton);
        StatusDropdown.AddStyleClass(SecApartmentStyles.StyleClassOptionButton);

        IconDropdown.OptionStyleClasses.Add(SecApartmentStyles.StyleClassButtonRed);
        StatusDropdown.OptionStyleClasses.Add(SecApartmentStyles.StyleClassButtonRed);

        SquadNameLabel.FontColorOverride = SecApartmentStyles.HeadingColor;
        MembersCountLabel.FontColorOverride = SecApartmentStyles.TextColor;
        MembersHeaderLabel.FontColorOverride = SecApartmentStyles.SubHeadingColor;
    }

    private void UpdateUI()
    {
        SquadNameLabel.Text = Squad.Name.ToUpperInvariant();
        SquadNameEdit.Text = Squad.Name;
        SquadDescriptionLabel.Text = string.IsNullOrWhiteSpace(Squad.Description)
            ? Loc.GetString("sec-apartment-squad-no-desc") : Squad.Description;
        SquadDescriptionEdit.Text = Squad.Description;

        SquadLocationLabel.Text = Loc.GetString("sec-apartment-unknown");
        SquadLocationLabel.FontColorOverride = SecApartmentStyles.TabInactiveColor;

        IconDropdown.SelectId((int)Squad.IconId);
        StatusDropdown.SelectId((int)Squad.Status);

        MembersCountLabel.Text = Loc.GetString("sec-apartment-squad-members", ("count", Squad.Members.Count));

        UpdateEditMode();
    }

    private void SetupIconDropdown()
    {
        IconDropdown.Clear();
        foreach (SquadIconNum icon in Enum.GetValues(typeof(SquadIconNum)))
        {
            IconDropdown.AddItem(GetIconText(icon), (int)icon);
        }

        IconDropdown.OnItemSelected += args =>
        {
            IconDropdown.SelectId(args.Id);
            var icon = (SquadIconNum)args.Id;
            OnIconChanged?.Invoke(icon);
        };
    }

    private void UpdateEditMode()
    {
        SquadNameLabel.Visible = !_isEditingName;
        IconDropdown.Visible = !_isEditingName;
        SquadNameEdit.Visible = _isEditingName;
        SaveNameButton.Visible = _isEditingName;
        RenameButton.Visible = !_isEditingName;

        SquadDescriptionLabel.Visible = !_isEditingDescription;
        SquadDescriptionEdit.Visible = _isEditingDescription;
        SaveDescriptionButton.Visible = _isEditingDescription;
        EditDescriptionButton.Visible = !_isEditingDescription;
    }

    private void UpdateMembersList()
    {
        MembersContainer.Children.Clear();

        if (Squad.Members.Count == 0)
        {
            var emptyLabel = new Label
            {
                Text = Loc.GetString("sec-apartment-squad-no-members"),
                FontColorOverride = SecApartmentStyles.TabInactiveColor,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 5)
            };
            MembersContainer.AddChild(emptyLabel);
            return;
        }

        foreach (var member in Squad.Members)
        {
            var memberEntry = CreateMemberEntry(member);
            MembersContainer.AddChild(memberEntry);
        }
    }

    private PanelContainer CreateMemberEntry(CrewMemberInfo member)
    {
        Color backgroundColor;
        Color borderColor;

        if (member.SensorStatus == null || !member.SensorStatus.IsAlive)
        {
            backgroundColor = Color.FromHex("#1a0a0a");
            borderColor = Color.FromHex("#990000");
        }
        else
        {
            backgroundColor = Color.FromHex("#3a0f0f");
            borderColor = Color.FromHex("#ff6666");
        }

        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = backgroundColor,
                BorderColor = borderColor,
                BorderThickness = new Thickness(1),
                ContentMarginBottomOverride = 4,
                ContentMarginLeftOverride = 8,
                ContentMarginRightOverride = 8,
                ContentMarginTopOverride = 4
            }
        };

        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            SeparationOverride = 8
        };

        var infoContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        var nameContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var nameLabel = new Label
        {
            Text = member.Name,
            FontColorOverride = member.SensorStatus?.IsAlive == false
                ? Color.FromHex("#888888")
                : SecApartmentStyles.TextColor,
            FontOverride = _styles.GetBoldFont(12)
        };

        nameContainer.AddChild(nameLabel);

        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "alive");

        if (member.SensorStatus != null)
        {
            if (!member.SensorStatus.IsAlive)
            {
                specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "dead");
            }
            else if (member.SensorStatus.DamagePercentage != null)
            {
                var index = MathF.Round(4f * member.SensorStatus.DamagePercentage.Value);

                if (index >= 5)
                    specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "critical");
                else
                    specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Alerts/human_crew_monitoring.rsi"), "health" + index);
            }
        }/*
        else
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/health_icons.rsi"), "Critical");
        }*///всётаки оставлю чуть больше шансов антагам :D

        var statusIcon = new AnimatedTextureRect
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 1, 3, 0),
        };

        statusIcon.SetFromSpriteSpecifier(specifier);
        statusIcon.DisplayRect.TextureScale = new Vector2(2f, 2f);

        nameContainer.AddChild(statusIcon);

        infoContainer.AddChild(nameContainer);

        var jobContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        var jobLabel = new Label
        {
            Text = member.JobTitle,
            FontColorOverride = SecApartmentStyles.SubTextColor,
            FontOverride = _styles.GetRegularFont(10),
            Margin = new Thickness(0, 0, 5, 0)
        };

        jobContainer.AddChild(jobLabel);

        SpriteSpecifier? iconSpecifier = null;
        if (_prototypeManager.HasIndex<JobIconPrototype>(member.JobIcon))
            iconSpecifier = _prototypeManager.Index<JobIconPrototype>(member.JobIcon).Icon;
        else if (_prototypeManager.HasIndex<StatusIconPrototype>(member.JobIcon))
            iconSpecifier = _prototypeManager.Index<StatusIconPrototype>(member.JobIcon).Icon;

        if (iconSpecifier != null)
        {
            var icon = new TextureRect()
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Left,
                Texture = _sprite.Frame0(iconSpecifier),
                Margin = new Thickness(0, 0, 4, 0),
                Stretch = TextureRect.StretchMode.KeepCentered
            };

            jobContainer.AddChild(icon);
        }

        infoContainer.AddChild(jobContainer);

        var removeButton = new Button
        {
            Text = Loc.GetString("sec-apartment-squad-remove-name"),
            ToolTip = Loc.GetString("sec-apartment-squad-remove-tooltip"),
            MinWidth = 30
        };
        removeButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);

        removeButton.OnPressed += _ =>
        {
            OnRemoveMemberPressed?.Invoke(member.MemberId);
        };

        container.AddChild(infoContainer);
        container.AddChild(removeButton);

        panel.AddChild(container);

        _memberPanels[member.MemberId] = panel;
        return panel;
    }

    public void UpdateSensorStatuses(Dictionary<string, SuitSensorStatus?> statuses,
        Dictionary<string, (string Location, bool HasLocation)> squadLocations)
    {
        foreach (var (memberId, panel) in _memberPanels)
        {
            if (statuses.TryGetValue(memberId, out var status))
                UpdateMemberSensorStatus(panel, status);
        }

        if (squadLocations.TryGetValue(Squad.SquadId, out var locationInfo))
            UpdateSquadLocation(locationInfo);
    }

    private void UpdateMemberSensorStatus(PanelContainer panel, SuitSensorStatus? status)
    {
        Color backgroundColor;
        Color borderColor;

        if (status == null || !status.IsAlive)
        {
            backgroundColor = Color.FromHex("#1a0a0a");
            borderColor = Color.FromHex("#990000");
        }
        else
        {
            backgroundColor = Color.FromHex("#3a0f0f");
            borderColor = Color.FromHex("#ff6666");
        }

        if (panel.PanelOverride is StyleBoxFlat styleBox)
        {
            styleBox.BackgroundColor = backgroundColor;
            styleBox.BorderColor = borderColor;
        }

        if (panel.Children.FirstOrDefault() is BoxContainer container)
        {
            var infoContainer = container.Children.OfType<BoxContainer>().FirstOrDefault();
            if (infoContainer != null)
            {
                var nameContainer = infoContainer.Children.OfType<BoxContainer>().FirstOrDefault();
                if (nameContainer != null)
                {
                    var nameLabel = nameContainer.Children.OfType<Label>().FirstOrDefault();
                    if (nameLabel != null)
                    {
                        nameLabel.FontColorOverride = status?.IsAlive == false
                            ? Color.FromHex("#888888")
                            : SecApartmentStyles.TextColor;
                    }

                    var statusIcon = nameContainer.Children.OfType<AnimatedTextureRect>().FirstOrDefault();
                    if (statusIcon != null)
                    {
                        SpriteSpecifier specifier = new SpriteSpecifier.Rsi(
                            new ResPath("Interface/Alerts/human_crew_monitoring.rsi"),
                            "alive"
                        );

                        if (status != null)
                        {
                            if (!status.IsAlive)
                            {
                                specifier = new SpriteSpecifier.Rsi(
                                    new ResPath("Interface/Alerts/human_crew_monitoring.rsi"),
                                    "dead"
                                );
                            }
                            else if (status.DamagePercentage != null)
                            {
                                var index = MathF.Round(4f * status.DamagePercentage.Value);
                                if (index >= 5)
                                    specifier = new SpriteSpecifier.Rsi(
                                        new ResPath("Interface/Alerts/human_crew_monitoring.rsi"),
                                        "critical"
                                    );
                                else
                                    specifier = new SpriteSpecifier.Rsi(
                                        new ResPath("Interface/Alerts/human_crew_monitoring.rsi"),
                                        "health" + index
                                    );
                            }
                        }/*
                        else
                        {
                            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/health_icons.rsi"), "Critical");
                        }*///всётаки оставлю больше шансов антагам :D

                        statusIcon.SetFromSpriteSpecifier(specifier);
                    }
                }
            }
        }
    }

    private void UpdateSquadLocation((string Location, bool HasLocation) locationInfo)
    {
        if (locationInfo.HasLocation && !string.IsNullOrWhiteSpace(locationInfo.Location))
        {
            SquadLocationLabel.Text = locationInfo.Location;
            SquadLocationLabel.FontColorOverride = SecApartmentStyles.TextColor;
        }
        else
        {
            SquadLocationLabel.Text = Loc.GetString("sec-apartment-unknown");
            SquadLocationLabel.FontColorOverride = SecApartmentStyles.TabInactiveColor;
        }
    }

    private void ToggleNameEdit()
    {
        _isEditingName = !_isEditingName;
        UpdateEditMode();

        if (_isEditingName)
        {
            SquadNameEdit.Text = Squad.Name;
            SquadNameEdit.GrabKeyboardFocus();
            SquadNameEdit.CursorPosition = SquadNameEdit.Text.Length;
        }
    }

    private void ToggleDescriptionEdit()
    {
        _isEditingDescription = !_isEditingDescription;
        UpdateEditMode();

        if (_isEditingDescription)
        {
            SquadDescriptionEdit.Text = Squad.Description ?? "";
            SquadDescriptionEdit.GrabKeyboardFocus();
        }
    }

    private void SaveName()
    {
        var newName = SquadNameEdit.Text.Trim();
        if (!string.IsNullOrWhiteSpace(newName) && newName != Squad.Name)
        {
            OnRenamePressed?.Invoke(newName);
        }
        _isEditingName = false;
        UpdateEditMode();
    }

    private void SaveDescription()
    {
        var description = SquadDescriptionEdit.Text.Trim();
        OnUpdateDescriptionPressed?.Invoke(description);
        _isEditingDescription = false;
        UpdateEditMode();
    }

    private string GetStatusText(SquadStatus status)
    {
        return status switch
        {
            SquadStatus.Active => Loc.GetString("sec-apartment-active"),
            SquadStatus.OnBreak => Loc.GetString("sec-apartment-on-break"),
            _ => Loc.GetString("sec-apartment-unknown")
        };
    }

    private string GetIconText(SquadIconNum icon)
    {
        return icon switch
        {
            SquadIconNum.Alpha => Loc.GetString("sec-apartment-icon-alpha"),
            SquadIconNum.Beta => Loc.GetString("sec-apartment-icon-beta"),
            SquadIconNum.Gamma => Loc.GetString("sec-apartment-icon-gamma"),
            SquadIconNum.Delta => Loc.GetString("sec-apartment-icon-delta"),
            SquadIconNum.Epsilon => Loc.GetString("sec-apartment-icon-epsilon"),
            SquadIconNum.Zeta => Loc.GetString("sec-apartment-icon-zeta"),
            SquadIconNum.Heta => Loc.GetString("sec-apartment-icon-heta"),
            SquadIconNum.Theta => Loc.GetString("sec-apartment-icon-theta"),
            SquadIconNum.Iota => Loc.GetString("sec-apartment-icon-iota"),
            SquadIconNum.Kappa => Loc.GetString("sec-apartment-icon-kappa"),
            SquadIconNum.Lambda => Loc.GetString("sec-apartment-icon-lambda"),
            SquadIconNum.Mu => Loc.GetString("sec-apartment-icon-mu"),
            SquadIconNum.Nu => Loc.GetString("sec-apartment-icon-nu"),
            SquadIconNum.Xi => Loc.GetString("sec-apartment-icon-xi"),
            SquadIconNum.Omicron => Loc.GetString("sec-apartment-icon-omicron"),
            SquadIconNum.Pi => Loc.GetString("sec-apartment-icon-pi"),
            SquadIconNum.Ro => Loc.GetString("sec-apartment-icon-ro"),
            SquadIconNum.Sigma => Loc.GetString("sec-apartment-icon-sigma"),
            SquadIconNum.Tau => Loc.GetString("sec-apartment-icon-tau"),
            SquadIconNum.Upsilon => Loc.GetString("sec-apartment-icon-upsilon"),
            SquadIconNum.Fi => Loc.GetString("sec-apartment-icon-fi"),
            SquadIconNum.Hi => Loc.GetString("sec-apartment-icon-hi"),
            SquadIconNum.Psi => Loc.GetString("sec-apartment-icon-psi"),
            SquadIconNum.Omega => Loc.GetString("sec-apartment-icon-omega"),
            _ => Loc.GetString("sec-apartment-unknown")
        };
    }
}
