using Content.Client.Corvax.SecApartment.Stylesheets;
using Content.Shared.SecApartment;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Corvax.SecApartment;

[GenerateTypedNameReferences]
public sealed partial class TimerEntryControl : PanelContainer
{
    private TimerEntry _timerEntry;
    private readonly SecApartmentStyles _styles;

    public TimeSpan RemainingTime => _timerEntry.RemainingTime;

    public Action? OnRemovePressed;

    public TimerEntryControl(TimerEntry timerEntry, SecApartmentStyles styles)
    {
        RobustXamlLoader.Load(this);

        _timerEntry = timerEntry;
        _styles = styles;

        RemoveButton.OnPressed += _ => OnRemovePressed?.Invoke();

        SetupStyles();
        UpdateDisplay();
    }

    private void SetupStyles()
    {
        PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#2a0a0a"),
            BorderColor = Color.FromHex("#ff4444"),
            BorderThickness = new Thickness(1),
            ContentMarginBottomOverride = 6,
            ContentMarginLeftOverride = 8,
            ContentMarginRightOverride = 8,
            ContentMarginTopOverride = 6
        };

        RemoveButton.AddStyleClass(SecApartmentStyles.StyleClassButtonRed);

        TimerLabel.FontOverride = _styles.GetBoldFont(12);
        TimeLabel.FontOverride = _styles.GetBoldFont(12);
        TotalTimeLabel.FontOverride = _styles.GetRegularFont(10);
    }

    public void UpdateTimer(TimerEntry timerEntry)
    {
        _timerEntry = timerEntry;
        UpdateDisplay();
    }

    private void UpdateDisplay()
    {
        TimerLabel.Text = _timerEntry.Label;

        var remaining = _timerEntry.RemainingTime;
        UpdateTimeLabel(remaining);

        TotalTimeLabel.Text = FormatTimeSpan(_timerEntry.TotalTime);
    }

    private void UpdateTimeLabel(TimeSpan remaining)
    {
        if (remaining < TimeSpan.Zero)
        {
            var overdue = -remaining;
            TimeLabel.Text = $"-{FormatTimeSpan(overdue)}";
            TimeLabel.FontColorOverride = Color.FromHex("#ff0000");
        }
        else
        {
            TimeLabel.Text = FormatTimeSpan(remaining);

            if (remaining.TotalSeconds < 30)
                TimeLabel.FontColorOverride = Color.FromHex("#ff3333");
            else if (remaining.TotalSeconds < 60)
                TimeLabel.FontColorOverride = Color.FromHex("#ff9933");
            else
                TimeLabel.FontColorOverride = Color.FromHex("#ff6666");
        }
    }

    private string FormatTimeSpan(TimeSpan timeSpan)
    {
        if (timeSpan.TotalHours >= 1)
        {
            return $"{(int)timeSpan.TotalHours:00}:{timeSpan.Minutes:00}:{timeSpan.Seconds:00}";
        }
        else
        {
            return $"{timeSpan.Minutes:00}:{timeSpan.Seconds:00}";
        }
    }
}
