using Content.Shared.Icarus;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Icarus;

[GenerateTypedNameReferences]
public sealed partial class IcarusTerminalWindow : DefaultWindow
{
    public event Action? FireButtonPressed;

    public IcarusTerminalWindow()
    {
        RobustXamlLoader.Load(this);

        FireButton.OnPressed += _ => FireButtonPressed?.Invoke();
    }

    public void UpdateState(IcarusTerminalUiState state)
    {
        switch (state.Status)
        {
            case IcarusTerminalStatus.FIRE_READY:
                FireButton.Disabled = false;
                break;
            default:
                FireButton.Disabled = true;
                break;
        }
    }
}
