using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Reserve.Revolutionary.UI;

[GenerateTypedNameReferences]
public sealed partial class ConsentRequestedMenu : FancyWindow
{
    public event Action? OnAccept;
    public event Action? OnDeny;
    public ConsentRequestedMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AcceptButton.OnPressed += _ => OnAccept?.Invoke();
        DenyButton.OnPressed += _ => OnDeny?.Invoke();
    }

    public void SetConverterName(string? text)
    {
        MessageText.Text = text == null ? Loc.GetString("rev-consent-window-convert-text-no-user") : Loc.GetString("rev-consent-window-convert-text", ("user", text));
    }
}


