using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs.PlayerTab;

[GenerateTypedNameReferences]
public sealed partial class PlayerTabEntry : ContainerButton
{
    public EntityUid? PlayerUid;

    public PlayerTabEntry(string username, string character, string identity, string job, string antagonist, string sponsor, StyleBox styleBox, bool connected)
    {
        RobustXamlLoader.Load(this);

        UsernameLabel.Text = username;
        if (!connected)
            UsernameLabel.StyleClasses.Add("Disabled");
        JobLabel.Text = job;
        CharacterLabel.Text = character;
        if (identity != character)
            CharacterLabel.Text += $" [{identity}]";
        AntagonistLabel.Text = antagonist;
        SponsorLabel.Text = sponsor;
        BackgroundColorPanel.PanelOverride = styleBox;
    }
}
