using Content.Client.Xenonids.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CorvaxNext.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryStepButton : XenoChoiceControl
{
    public EntityUid Step { get; set; }

    public SurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
    }
}
