using System.Linq;
using Content.Corvax.Interfaces.Shared;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using static Content.Client.Corvax.SponsorOnlyHelpers; // Corvax-Sponsors

namespace Content.Client.Humanoid;

[GenerateTypedNameReferences]
public sealed partial class MarkingPicker : Control
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
	private ISharedSponsorsManager? _sponsorsManager; // Corvax-Sponsors
    private MarkingsViewModel? _markingsModel;

    public MarkingPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        IoCManager.Instance!.TryResolveType(out _sponsorsManager); // Corvax-Sponsors

        UpdateMarkings();
    }

    public void SetModel(MarkingsViewModel model)
    {
        _markingsModel = model;

        _markingsModel.OrganDataChanged += UpdateMarkings;
        _markingsModel.EnforcementsChanged += UpdateMarkings;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel?.OrganDataChanged += UpdateMarkings;
        _markingsModel?.EnforcementsChanged += UpdateMarkings;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel?.OrganDataChanged -= UpdateMarkings;
        _markingsModel?.EnforcementsChanged -= UpdateMarkings;
            // Corvax-Sponsors-Start
            if (marking.SponsorOnly)
                item.Text += GetSponsorOnlySuffix();
            if (marking.SponsorOnly && _sponsorsManager != null)
                item.Disabled = !_sponsorsManager.GetClientPrototypes().Contains(marking.ID);
            // Corvax-Sponsors-End
    }

    private void UpdateMarkings()
    {
        if (_markingsModel is null)
            return;

        OrganTabs.RemoveAllChildren();

        var i = 0;
        foreach (var (organ, organData) in _markingsModel.OrganData)
        {
            var control = new OrganMarkingPicker(_markingsModel, organ, organData.Layers, organData.Group);
            if (control.Empty)
                continue;

            OrganTabs.AddChild(control);
            OrganTabs.SetTabTitle(i, Loc.GetString($"markings-organ-{organ.Id}"));
            i++;
        }

        if (i > 0)
            OrganTabs.CurrentTab = 0;
        OrganTabs.TabsVisible = i > 1;
    }
}
