- type: job
  id: CentralCommandOfficial
  name: job-name-centcommoff
  description: job-description-centcommoff
  playTimeTracker: JobCentralCommandOfficial
  setPreference: false
  startingGear: CentcommGear
  icon: "JobIconNanotrasen"
  # Corvax-Start
  supervisors: job-supervisors-centcom
  # accessGroups:
  # - AllAccess
  access:
  - CentralCommand
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Lawyer
  - Cargo
  - Atmospherics
  - Medical
  - GenpopEnter
  - GenpopLeave
  # Corvax-End
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentcommGear
  # Corvax-Start
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficial
    back: ClothingBackpackSatchelLeather
    neck: ClothingNeckTieSerious
    shoes: ClothingShoesColorBlack
    eyes: ClothingEyesGlassesCommand
    gloves: ClothingHandsGlovesColorBlack
    id: CentcomPDA
    ears: ClothingHeadsetCentCom
    belt: BoxFolderClipboardThreePapers
    pocket1: WeaponDisabler
    pocket2: Flash
  storage:
    back:
    - DrinkWaterBottleFull
    - Zipties
  # Corvax-End

- type: chameleonOutfit
  id: CentralCommandOfficialOutfit
  job: CentralCommandOfficial
  hasMindShield: true
  equipment:
    neck: ClothingNeckScarfStripedCentcom
    mask: ClothingMaskGasCentcom
