using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;

namespace Content.Client.Corvax.Donate;

[GenerateTypedNameReferences]
public sealed partial class DonateWindow : PanelContainer
{
    public DonateWindow()
    {
        RobustXamlLoader.Load(this);
        var uri = IoCManager.Resolve<IUriOpener>();
        SiteButton.OnPressed += _ => uri.OpenUri("https://ss14.ru/donate");
        BoostyButton.OnPressed += _ => uri.OpenUri("https://boosty.to/corvax");
        WikiButton.OnPressed += _ => uri.OpenUri("https://station14.ru/wiki");
        DiscordButton.OnPressed += _ => uri.OpenUri("https://discord.ss14.ru");
    }
}
