- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: StationGoal
      goals:
      - Singularity
      - SolarPanels
      - Artifacts
      - Bank
      - Zoo
      - MiningOutpost
      - Tesla
      - SecurityTraining
      - ShuttleMed
      - ShuttleSec
      - ShuttleRnd
      - ShuttleSrv
      - ShuttleEmergency
      - Theatre
      - CellAI
      - Botany
      - Bunker

- type: entity
  id: BaseStationSiliconLawNTDefault
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault
