- type: entity
  id: BaseStationGoal
  abstract: true
  components:
  - type: StationGoal
    goals:
    - Zoo
    - SolarPanels
    - ShuttleCargo
    - ShuttleMed
    - ShuttleRnd
    - ShuttleEmergency
    - LivingOutpost
    - Bank
    - CellAI
    - Modification
    - Anomalies
    - Borgs
    - Artifacts
    - Theatre
    - Celebration
    - Exposition
    - DefenceEvent

- type: entity
  id: BaseStationSiliconLawNTDefault
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault
