using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Client.VendingMachines.UI;
using Content.Shared._CorvaxNext.Medical.SmartFridge;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface;
using Robust.Shared.Prototypes;

namespace Content.Client._CorvaxNext.Medical.SmartFridge.UI;

[GenerateTypedNameReferences]
public sealed partial class SmartFridgeMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly Dictionary<EntProtoId, EntityUid> _dummies = [];

    public event Action<GUIBoundKeyEventArgs, ListData>? OnItemSelected;

    public SmartFridgeMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        VendingContents.SearchBar = SearchBar;
        VendingContents.DataFilterCondition += DataFilterCondition;
        VendingContents.GenerateItem += GenerateButton;
        VendingContents.ItemKeyBindDown += (args, data) => OnItemSelected?.Invoke(args, data);
    }

    private static bool DataFilterCondition(string filter, ListData data)
    {
        if (data is not VendorItemsListData { ItemText: var text })
            return false;

        return string.IsNullOrEmpty(filter) || text.Contains(filter, StringComparison.CurrentCultureIgnoreCase);
    }

    private void GenerateButton(ListData data, ListContainerButton button)
    {
        if (data is not VendorItemsListData { ItemProtoID: var protoId, ItemText: var text })
            return;

        button.AddChild(new VendingMachineItem(protoId, text));
        button.ToolTip = text;
    }

    public void Populate(List<SmartFridgeInventoryItem> inventory)
    {
        if (inventory.Count == 0)
        {
            SearchBar.Visible = false;
            VendingContents.Visible = false;
            OutOfStockLabel.Visible = true;
            return;
        }

        SearchBar.Visible = true;
        VendingContents.Visible = true;
        OutOfStockLabel.Visible = false;

        var listData = new List<VendorItemsListData>();

        for (var i = 0; i < inventory.Count; i++)
        {
            var entry = inventory[i];

            if (!_prototypeManager.TryIndex(entry.Id, out var prototype))
                continue;

            if (!_dummies.TryGetValue(entry.Id, out var dummy))
            {
                dummy = _entityManager.Spawn(entry.Id);
                _dummies.Add(entry.Id, dummy);
            }

            var itemText = $"{entry.ItemName} [{entry.Quantity}]";
            listData.Add(new VendorItemsListData(prototype.ID, itemText, i));
        }

        VendingContents.PopulateList(listData);
    }
}
