name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'IanComradeBot'
    permissions:
      contents: read
      pull-requests: write
    runs-on: [self-hosted]
    steps:
    - uses: actions/labeler@v5
