name: "Labels: Branch stable"

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'stable'

jobs:
  add_label:
    runs-on: [self-hosted]
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "Branch: Stable"
