name: "Labels: Approve"

on:
  pull_request_review:
    types: [submitted]

jobs:
  remove_label:
    permissions:
      pull-requests: write
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          Status: Needs Review
          Status: Awaiting Changes
