name: Publish Testing

concurrency:
  group: publish-testing
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
  - cron: '0 10 * * *'

jobs:
  build:
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.0.x
      env:
        DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet

    - name: Set DOTNET_ROOT and PATH
      run: |
        echo "DOTNET_ROOT=${{ runner.temp }}/.dotnet" >> $GITHUB_ENV
        echo "${{ runner.temp }}/.dotnet" >> $GITHUB_PATH

    - name: Check .NET installation
      run: dotnet --info

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1

    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py --fork-id wizards-testing
      env:
        PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        GITHUB_REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
