name: YAML Linter

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter
    if: github.actor != 'IanComradeBot' && github.event.pull_request.draft == false
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup submodule
        run: |
          git submodule update --init --recursive
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
        env:
          DOTNET_INSTALL_DIR: ${{ runner.temp }}/.dotnet
      - name: Set DOTNET_ROOT and PATH
        run: |
          echo "DOTNET_ROOT=${{ runner.temp }}/.dotnet" >> $GITHUB_ENV
          echo "${{ runner.temp }}/.dotnet" >> $GITHUB_PATH
      - name: Check .NET installation
        run: dotnet --info
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Run Linter
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
